### ISSUE TITLE
todo List

### ISSUE THREAD

**Issue by thrypuro** [thrypuro/top-BFT#1]
- [ ] Integrate boostASIO into the server 
- [ ] Finish the entire algorithm
- [ ] Have an actual http server that people can interact with
- [ ] Post the original paper pdf
